"""Spec-derived reference data: searchable fields, enums, and framework keys.

Field lists are taken from the entity attribute schemas in the Secureframe
OpenAPI document (vendored at docs/openapi.yaml). They are the fields available
to the Lucene ``q`` parameter, surfaced as MCP resources so callers can discover
what is filterable without reading the API docs or guessing.
"""

from __future__ import annotations

# Searchable/returned attribute fields per resource, keyed by the friendly
# resource name used in tool/resource names.
SEARCHABLE_FIELDS: dict[str, list[str]] = {
    "controls": [
        "at_risk_test_count",
        "author_name",
        "created_at",
        "custom",
        "description",
        "disabled_justification",
        "disabled_test_count",
        "enabled",
        "failing_test_count",
        "framework_ids",
        "framework_keys",
        "framework_requirement_keys",
        "health_status",
        "implementation_date",
        "implementation_status",
        "key",
        "name",
        "owner_assigned_at",
        "owner_name",
        "passing_test_count",
        "updated_at",
    ],
    "tests": [
        "created_at",
        "custom",
        "description",
        "detailed_remediation_steps",
        "disabled_justification",
        "enabled",
        "enabled_field_updated_by_user_name",
        "failure_message",
        "first_failed_at",
        "framework_ids",
        "framework_keys",
        "health_status",
        "key",
        "last_evaluated",
        "last_passed_at",
        "next_due_date",
        "owner_assigned_at",
        "owner_name",
        "pass",
        "passed_with_upload",
        "passed_with_upload_justification",
        "promote_at",
        "promoted_by_name",
        "recommended_action",
        "required_implementation_date",
        "resource_category",
        "test_domain",
        "test_function",
        "test_interval_seconds",
        "test_type",
        "title",
        "tolerance_window_seconds",
        "updated_at",
        "vendor_name",
    ],
    "users": [
        "access_role",
        "active",
        "active_source",
        "created_at",
        "department_id",
        "email",
        "employee_type",
        "end_date",
        "first_name",
        "image_url",
        "in_audit_scope",
        "invited",
        "invited_at",
        "last_name",
        "manager_name",
        "middle_name",
        "name",
        "onboarding_status",
        "personnel_status",
        "preferred_first_name",
        "role",
        "start_date",
        "title",
        "updated_at",
    ],
    "devices": [
        "created_at",
        "cpu",
        "device_name",
        "hard_drive_encrypted",
        "in_audit_scope",
        "last_checkin_at",
        "local_firewall_enabled",
        "mac_address",
        "make",
        "memory",
        "model",
        "native_anti_virus_enabled",
        "os",
        "out_of_audit_scope_reason",
        "password_enforcement_enabled",
        "remote_ip",
        "serial_number",
        "session_timeout_enabled",
        "updated_at",
    ],
    "risks": [
        "annualized_rate_of_occurrence",
        "asset_value",
        "categories",
        "cia",
        "departments",
        "description",
        "exposure_factor",
        "notes",
        "reference_url",
        "related_tickets",
        "reported_by",
        "responsible_team",
        "source",
        "status",
        "treatment",
        "uncertainty",
        "created_at",
        "updated_at",
        "owner_id",
        "custom_risk_id",
    ],
    "vendors": [
        "archived",
        "archived_at",
        "audit_scopes",
        "authentication_type",
        "data_collected",
        "date_of_engagement",
        "domain",
        "environment_types",
        "last_reviewed_at",
        "name",
        "operational_reliance",
        "owner_id",
        "risk_level",
        "security_url",
        "services",
        "terminated_at",
        "two_factor_enabled",
        "updated_at",
    ],
    "tprm_vendors": [
        "archived",
        "archived_at",
        "authentication_type",
        "created_at",
        "data_collected",
        "environment_types",
        "last_reviewed_at",
        "name",
        "owner_id",
        "risk_level",
        "security_url",
        "services_provided",
        "two_factor_enabled",
        "updated_at",
        "vendor_status",
        "website",
    ],
    "frameworks": [
        "applicable_controls_count",
        "applicable_framework_requirements_count",
        "at_risk_test_count",
        "created_at",
        "description",
        "disabled_test_count",
        "failing_test_count",
        "key",
        "title",
        "passing_test_count",
        "updated_at",
    ],
    "framework_requirements": [
        "company_id",
        "created_at",
        "description",
        "enabled",
        "health_status",
        "key",
        "name",
        "updated_at",
    ],
    "cloud_resources": [
        "cloud_resource_type",
        "created_at",
        "in_audit_scope",
        "out_of_audit_scope_reason",
        "region",
        "tags",
        "third_party_id",
        "vendor_name",
        "updated_at",
    ],
    "repositories": [
        "created_at",
        "name",
        "in_audit_scope",
        "out_of_audit_scope_reason",
        "private",
        "third_party_id",
        "vendor_name",
        "updated_at",
    ],
    "user_accounts": [
        "active",
        "created_at",
        "email",
        "first_name",
        "has_user",
        "last_name",
        "third_party_id",
        "username",
        "vendor_name",
        "updated_at",
    ],
    "integration_connections": ["name", "status", "vendor_name", "updated_at"],
    "comments": [
        "commentable_id",
        "commentable_type",
        "created_at",
        "content",
        "updated_at",
    ],
    "trust_center_requests": [
        "company_name",
        "created_at",
        "document_security",
        "requester_name",
        "job_title",
        "reason",
        "reviewed",
        "updated_at",
        "email",
    ],
}

# Known enumerated value sets for common filter fields.
ENUMS: dict[str, list[str]] = {
    "control.health_status": ["healthy", "unhealthy", "draft"],
    "control.implementation_status": ["implemented", "not_implemented"],
    "test.health_status": ["pass", "fail", "disabled"],
    "test.test_type": ["integration", "upload"],
    "user.employee_type": [
        "employee",
        "contractor",
        "non_employee",
        "auditor",
        "external",
    ],
    "framework_requirement.health_status": ["pass", "fail", "na", "draft"],
    "vendor.risk_level": ["Low", "Medium", "High"],
    "vendor.status": ["draft", "completed"],
    "repository.vendor_name": ["Github", "Gitlab", "Bitbucket"],
}

# Common framework keys for the ``framework_keys`` field.
FRAMEWORK_KEYS: list[str] = [
    "soc2_alpha",
    "iso27001",
    "iso27001_2022",
    "CIS_IG1",
    "hipaa",
    "cmmc_l2",
    "FedRAMP_Low",
    "FedRAMP_Moderate",
    "FedRAMP_High",
    "FedRAMP_20x",
    "gdpr",
    "pci_dss",
    "nist_csf",
]
